FROM cgr.dev/chainguard/minio@sha256:bd014394a80898e68c149f2311fdf8d5a2c2f3bb2c33b9327ae6d02b4b065ae1 AS legacy
FROM rclone/rclone:1.75.1 AS transfer
FROM chrislusf/seaweedfs:4.47
COPY --from=legacy /usr/bin/minio /usr/local/bin/legacy-minio
COPY --from=transfer /usr/local/bin/rclone /usr/local/bin/rclone
COPY docker/storage/start.sh /usr/local/bin/craftplan-storage
ENTRYPOINT ["/bin/sh", "/usr/local/bin/craftplan-storage"]
CMD []
