import Config

# Do not include metadata nor timestamps in development logs
#       certfile: "priv/cert/selfsigned.pem"
#       port: 4001,
# in production as building large stacktraces may be expensive.
# Configure your database
config :logger, :console, format: "[$level] $message\n"

config :microcraft, Microcraft.Repo,
  # For development, we disable any cache and enable
  # debugging and code reloading.
  #
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # to bundle .js and .css sources.
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "microcraft_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :microcraft, MicrocraftWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Watch static and templates for browser reloading.

  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  # ## SSL Support
  #
  # In order to use HTTPS in development, a self-signed
  # certificate can be generated by running the following
  # Mix task:
  #
  #     mix phx.gen.cert
  #
  # Run `mix help phx.gen.cert` for more information.
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "NlbIq9/9aO9+5xxg8ESxxFI7ay172FlEI5IVJvhLx50ZcZbWLjV1L1ito7aZ0fiM",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:microcraft, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:microcraft, ~w(--watch)]},
    storybook_tailwind: {Tailwind, :install_and_run, [:storybook, ~w(--watch)]}
  ]

config :microcraft, MicrocraftWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      # Enable dev routes for dashboard and mailbox
      #
      # The `http:` config above can be replaced with:
      #
      #     https: [
      ~r"lib/microcraft_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"storybook/.*(exs)$"
    ]
  ]

config :microcraft, dev_routes: true, token_signing_secret: "1Y4H7uJJNzu5KtTktCIrtiyGZ+A0eBS9"

#       cipher_suite: :strong,
# Include HEEx debug annotations as HTML comments in rendered markup
#     ],
#       keyfile: "priv/cert/selfsigned_key.pem",
# configured to run both http and https servers on
#
# different ports.
config :phoenix, :plug_init_mode, :runtime
# If desired, both `http:` and `https:` keys can be
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Set a higher stacktrace during development. Avoid configuring such
# Disable swoosh api client as it is only required for production adapters.
# Initialize plugs at runtime for faster development compilation

config :swoosh, :api_client, false
