import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This

config :craftscale, CraftScaleWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :logger, level: :info

# Configures Swoosh API Client
# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
# Disable Swoosh Local Memory Storage
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: CraftScale.Finch
config :swoosh, local: false
