defmodule Craftday.Repo.Migrations.AddOrderDeliveryDate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_orders) do
      add :delivery_date, :utc_datetime, null: false
    end
  end

  def down do
    alter table(:orders_orders) do
      remove :delivery_date
    end
  end
end
