defmodule Microcraft.Repo.Migrations.UpdateOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_orders) do
      remove :customer_name
    end
  end

  def down do
    alter table(:orders_orders) do
      add :customer_name, :text, null: false
    end
  end
end
