defmodule Craftplan.Repo.Migrations.AddOrderReferenceId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_orders) do
      modify :reference, :text
    end

    create unique_index(:orders_orders, [:reference], name: "orders_orders_reference_index")
  end

  def down do
    drop_if_exists unique_index(:orders_orders, [:reference],
                     name: "orders_orders_reference_index"
                   )

    alter table(:orders_orders) do
      modify :reference, :text
    end
  end
end
