defmodule Craftplan.Repo.Migrations.CreateOrganizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :status, :text, null: false, default: "active"
      add :billing_plan, :text, null: false, default: "starter"
      add :preferences, :map, null: false, default: %{}
    end

    create unique_index(:organizations, [:slug], name: "organizations_slug_index")
  end

  def down do
    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_slug_index")

    drop table(:organizations)
  end
end
