defmodule Craftplan.Repo.Migrations.AddOrderUnitPrice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_items) do
      add :unit_price, :money_with_currency, default: fragment("('USD', 0)")
    end
  end

  def down do
    alter table(:orders_items) do
      remove :unit_price
    end
  end
end
