defmodule Craftplan.Repo.Migrations.SyncOrganizationsSnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'settings_tenants_slug_index'
      ) THEN
        EXECUTE 'ALTER INDEX settings_tenants_slug_index RENAME TO organizations_slug_index';
      END IF;
    END;
    $$;
    """)
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'organizations_slug_index'
      ) THEN
        EXECUTE 'ALTER INDEX organizations_slug_index RENAME TO settings_tenants_slug_index';
      END IF;
    END;
    $$;
    """)
  end
end
