defmodule Craftplan.Repo.Migrations.AddUnitsPerRunToLaborSteps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_labor_steps) do
      add :units_per_run, :decimal, null: false, default: "1"
    end
  end

  def down do
    alter table(:catalog_labor_steps) do
      remove :units_per_run
    end
  end
end
