defmodule Craftday.Repo.Migrations.AddCarts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cart_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :bigint, null: false, default: 1
      add :price, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :cart_id, :uuid, null: false
      add :product_id, :uuid, null: false
    end

    create table(:cart, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:cart_items) do
      modify :cart_id,
             references(:cart,
               column: :id,
               name: "cart_items_cart_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "cart_items_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cart) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:cart) do
      remove :updated_at
      remove :inserted_at
    end

    drop constraint(:cart_items, "cart_items_cart_id_fkey")

    drop constraint(:cart_items, "cart_items_product_id_fkey")

    alter table(:cart_items) do
      modify :product_id, :uuid
      modify :cart_id, :uuid
    end

    drop table(:cart)

    drop table(:cart_items)
  end
end
