defmodule Microcraft.Repo.Migrations.AddOrderReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_orders) do
      modify :status, :text, default: "created"
      add :reference, :text, null: false
    end

    alter table(:catalog_products) do
      modify :status, :text, default: "draft"
    end
  end

  def down do
    alter table(:catalog_products) do
      modify :status, :text, default: "idea"
    end

    alter table(:orders_orders) do
      remove :reference
      modify :status, :text, default: "pending"
    end
  end
end
