defmodule Craftplan.Repo.Migrations.AddProductPhotos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_products) do
      add :photos, {:array, :text}, default: []
      add :featured_photo, :text
    end
  end

  def down do
    alter table(:catalog_products) do
      remove :featured_photo
      remove :photos
    end
  end
end
