defmodule Craftplan.Repo.Migrations.AddOrderTotalsAndCurrency do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_orders) do
      add :currency, :text, null: false, default: "USD"
      add :subtotal, :decimal, null: false, default: "0"
      add :tax_total, :decimal, null: false, default: "0"
      add :shipping_total, :decimal, null: false, default: "0"
      add :discount_total, :decimal, null: false, default: "0"
      add :total, :decimal, null: false, default: "0"
      add :paid_at, :utc_datetime
    end
  end

  def down do
    alter table(:orders_orders) do
      remove :paid_at
      remove :total
      remove :discount_total
      remove :shipping_total
      remove :tax_total
      remove :subtotal
      remove :currency
    end
  end
end
