defmodule Craftplan.Repo.Migrations.LotsAndBatches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders_production_batches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :batch_code, :text, null: false
      add :produced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id,
          references(:catalog_products,
            column: :id,
            name: "orders_production_batches_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :bom_id,
          references(:catalog_boms,
            column: :id,
            name: "orders_production_batches_bom_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:orders_production_batches, [:batch_code],
             name: "orders_production_batches_batch_code_index",
             unique: true
           )

    alter table(:orders_items) do
      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_items_production_batch_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:orders_item_lots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_used, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_item_id,
          references(:orders_items,
            column: :id,
            name: "orders_item_lots_order_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :lot_id, :uuid, null: false
    end

    alter table(:inventory_movements) do
      add :lot_id, :uuid
    end

    create table(:inventory_lots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_item_lots) do
      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "orders_item_lots_lot_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_movements) do
      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "inventory_movements_lot_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_lots) do
      add :lot_code, :text, null: false
      add :expiry_date, :date
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_lots_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :supplier_id,
          references(:inventory_suppliers,
            column: :id,
            name: "inventory_lots_supplier_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:inventory_lots, [:supplier_id], name: "inventory_lots_supplier_id_index")

    create index(:inventory_lots, [:material_id], name: "inventory_lots_material_id_index")

    create index(:inventory_lots, [:lot_code],
             name: "inventory_lots_lot_code_index",
             unique: true
           )
  end

  def down do
    drop constraint(:inventory_lots, "inventory_lots_material_id_fkey")

    drop constraint(:inventory_lots, "inventory_lots_supplier_id_fkey")

    drop_if_exists index(:inventory_lots, [:lot_code], name: "inventory_lots_lot_code_index")

    drop_if_exists index(:inventory_lots, [:material_id],
                     name: "inventory_lots_material_id_index"
                   )

    drop_if_exists index(:inventory_lots, [:supplier_id],
                     name: "inventory_lots_supplier_id_index"
                   )

    alter table(:inventory_lots) do
      remove :supplier_id
      remove :material_id
      remove :updated_at
      remove :inserted_at
      remove :received_at
      remove :expiry_date
      remove :lot_code
    end

    drop constraint(:inventory_movements, "inventory_movements_lot_id_fkey")

    alter table(:inventory_movements) do
      modify :lot_id, :uuid
    end

    drop constraint(:orders_item_lots, "orders_item_lots_lot_id_fkey")

    alter table(:orders_item_lots) do
      modify :lot_id, :uuid
    end

    drop table(:inventory_lots)

    alter table(:inventory_movements) do
      remove :lot_id
    end

    drop constraint(:orders_item_lots, "orders_item_lots_order_item_id_fkey")

    drop table(:orders_item_lots)

    drop constraint(:orders_items, "orders_items_production_batch_id_fkey")

    alter table(:orders_items) do
      remove :production_batch_id
    end

    drop constraint(:orders_production_batches, "orders_production_batches_product_id_fkey")

    drop constraint(:orders_production_batches, "orders_production_batches_bom_id_fkey")

    drop_if_exists index(:orders_production_batches, [:batch_code],
                     name: "orders_production_batches_batch_code_index"
                   )

    drop table(:orders_production_batches)
  end
end
