defmodule Craftplan.Repo.Migrations.AddBatchingCore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_production_batches) do
      remove :produced_at
      add :planned_qty, :decimal, null: false, default: "0"
      add :produced_qty, :decimal, null: false, default: "0"
      add :scrap_qty, :decimal, null: false, default: "0"
      add :status, :text, null: false, default: "open"
      add :notes, :text
      add :bom_version, :bigint
      add :components_map, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
    end

    create table(:orders_production_batch_lots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_used, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_production_batch_lots_production_batch_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :lot_id,
          references(:inventory_lots,
            column: :id,
            name: "orders_production_batch_lots_lot_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:orders_production_batch_lots, [:lot_id],
             name: "orders_production_batch_lots_lot_idx"
           )

    create index(:orders_production_batch_lots, [:production_batch_id],
             name: "orders_production_batch_lots_batch_idx"
           )

    create table(:orders_item_batch_allocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :planned_qty, :decimal, null: false, default: "0"
      add :completed_qty, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_item_batch_allocations_production_batch_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :order_item_id,
          references(:orders_items,
            column: :id,
            name: "orders_item_batch_allocations_order_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:orders_item_batch_allocations, [:production_batch_id],
             name: "orders_item_batch_allocations_batch_idx"
           )

    create index(:orders_item_batch_allocations, [:order_item_id],
             name: "orders_item_batch_allocations_item_idx"
           )

    create index(:orders_item_batch_allocations, [:production_batch_id, :order_item_id],
             name: "orders_item_batch_allocations_unique_pair",
             unique: true
           )
  end

  def down do
    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_production_batch_id_fkey"
         )

    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_order_item_id_fkey"
         )

    drop_if_exists index(:orders_item_batch_allocations, [:production_batch_id, :order_item_id],
                     name: "orders_item_batch_allocations_unique_pair"
                   )

    drop_if_exists index(:orders_item_batch_allocations, [:order_item_id],
                     name: "orders_item_batch_allocations_item_idx"
                   )

    drop_if_exists index(:orders_item_batch_allocations, [:production_batch_id],
                     name: "orders_item_batch_allocations_batch_idx"
                   )

    drop table(:orders_item_batch_allocations)

    drop constraint(
           :orders_production_batch_lots,
           "orders_production_batch_lots_production_batch_id_fkey"
         )

    drop constraint(:orders_production_batch_lots, "orders_production_batch_lots_lot_id_fkey")

    drop_if_exists index(:orders_production_batch_lots, [:production_batch_id],
                     name: "orders_production_batch_lots_batch_idx"
                   )

    drop_if_exists index(:orders_production_batch_lots, [:lot_id],
                     name: "orders_production_batch_lots_lot_idx"
                   )

    drop table(:orders_production_batch_lots)

    alter table(:orders_production_batches) do
      remove :completed_at
      remove :started_at
      remove :components_map
      remove :bom_version
      remove :notes
      remove :status
      remove :scrap_qty
      remove :produced_qty
      remove :planned_qty
      add :produced_at, :utc_datetime
    end
  end
end
