defmodule Craftplan.Repo.Migrations.AdvancedRecipeVersioning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      add :advanced_recipe_versioning, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:settings) do
      remove :advanced_recipe_versioning
    end
  end
end
