defmodule Craftday.Repo.Migrations.AddConsumedAtAndConsumptionChange do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_items) do
      add :consumed_at, :utc_datetime
    end
  end

  def down do
    alter table(:orders_items) do
      remove :consumed_at
    end
  end
end
