defmodule Craftday.Repo.Migrations.AddCustomerReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_customers) do
      add :reference, :text, null: false
    end

    drop_if_exists unique_index(:crm_customers, [:email],
                     name: "crm_customers_unique_email_index"
                   )

    drop_if_exists unique_index(:crm_customers, [:phone],
                     name: "crm_customers_unique_phone_index"
                   )

    create unique_index(:crm_customers, [:email], name: "crm_customers_email_index")

    create unique_index(:crm_customers, [:phone], name: "crm_customers_phone_index")

    create unique_index(:crm_customers, [:reference], name: "crm_customers_reference_index")
  end

  def down do
    drop_if_exists unique_index(:crm_customers, [:reference],
                     name: "crm_customers_reference_index"
                   )

    drop_if_exists unique_index(:crm_customers, [:phone], name: "crm_customers_phone_index")

    drop_if_exists unique_index(:crm_customers, [:email], name: "crm_customers_email_index")

    create unique_index(:crm_customers, [:phone], name: "crm_customers_unique_phone_index")

    create unique_index(:crm_customers, [:email], name: "crm_customers_unique_email_index")

    alter table(:crm_customers) do
      remove :reference
    end
  end
end
