defmodule CraftScale.Repo.Migrations.ChangeInstructionsToNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:catalog_recipes), :instructions, to: :notes

    alter table(:catalog_recipes) do
      modify :notes, :text
    end
  end

  def down do
    alter table(:catalog_recipes) do
      modify :instructions, :text
    end

    rename table(:catalog_recipes), :notes, to: :instructions
  end
end
