defmodule Craftday.Repo.Migrations.ChangeOrderStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_orders) do
      modify :status, :text, default: "unconfirmed"
      add :payment_status, :text, null: false, default: "pending"
    end
  end

  def down do
    alter table(:orders_orders) do
      remove :payment_status
      modify :status, :text, default: "created"
    end
  end
end
