defmodule Craftplan.Repo.Migrations.BomVersioning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:catalog_boms, [:product_id],
             name: "catalog_boms_one_active_per_product",
             unique: true,
             where: "status = 'active'"
           )

    alter table(:catalog_boms) do
      modify :version, :bigint, default: nil
    end

    alter table(:catalog_bom_rollups) do
      add_if_not_exists :components_map, :map, null: false, default: %{}
    end
  end

  def down do
    execute "ALTER TABLE catalog_bom_rollups DROP COLUMN IF EXISTS components_map"

    alter table(:catalog_boms) do
      modify :version, :bigint, default: 1
    end

    drop_if_exists index(:catalog_boms, [:product_id],
                     name: "catalog_boms_one_active_per_product"
                   )
  end
end
