defmodule Craftplan.Repo.Migrations.ImproveTraceabilityWorkflows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      add :food_business_name, :text
      add :food_business_address, :text
    end

    alter table(:inventory_lots) do
      add :received_quantity, :decimal, null: false, default: "0"
      add :status, :text, null: false, default: "available"
    end

    execute("""
    UPDATE inventory_lots AS lots
    SET received_quantity = received.total
    FROM (
      SELECT lot_id, SUM(quantity) AS total
      FROM inventory_movements
      WHERE lot_id IS NOT NULL AND quantity > 0
      GROUP BY lot_id
    ) AS received
    WHERE lots.id = received.lot_id
    """)

    alter table(:catalog_products) do
      add :shelf_life_days, :bigint
      add :storage_instructions, :text
      add :country_of_origin, :text
    end
  end

  def down do
    alter table(:catalog_products) do
      remove :country_of_origin
      remove :storage_instructions
      remove :shelf_life_days
    end

    alter table(:inventory_lots) do
      remove :status
      remove :received_quantity
    end

    alter table(:settings) do
      remove :food_business_address
      remove :food_business_name
    end
  end
end
