defmodule Craftplan.Repo.Migrations.AddResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      modify :shipping_flat, :money_with_currency, default: fragment("('USD', 0)")
    end
  end

  def down do
    alter table(:settings) do
      modify :shipping_flat, :decimal, default: "0"
    end
  end
end
