defmodule Craftplan.Repo.Migrations.AddNativeMaterialProduction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inventory_material_recipes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false
      add :yield_quantity, :decimal, null: false
      add :components, {:array, :map}, null: false, default: []
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_material_recipes_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:inventory_material_recipes, [:material_id, :version],
             name: "inventory_material_recipes_material_version_index"
           )

    create table(:inventory_material_batches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :planned_quantity, :decimal, null: false
      add :actual_quantity, :decimal, null: false
      add :lot_code, :text, null: false
      add :expiry_date, :date
      add :notes, :text
      add :recipe_snapshot, :map, null: false
      add :total_cost, :decimal, null: false
      add :completed_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_material_batches_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :output_lot_id,
          references(:inventory_lots,
            column: :id,
            name: "inventory_material_batches_output_lot_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:inventory_material_batches, [:lot_code],
             name: "inventory_material_batches_lot_code_index"
           )

    create unique_index(:inventory_material_batches, [:output_lot_id],
             name: "inventory_material_batches_output_lot_index"
           )

    create table(:inventory_material_batch_inputs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :unit_cost, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_batch_id,
          references(:inventory_material_batches,
            column: :id,
            name: "inventory_material_batch_inputs_material_batch_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :lot_id,
          references(:inventory_lots,
            column: :id,
            name: "inventory_material_batch_inputs_lot_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:inventory_material_batch_inputs, [:material_batch_id, :lot_id],
             name: "inventory_material_batch_inputs_batch_lot_index"
           )
  end

  def down do
    drop constraint(
           :inventory_material_batch_inputs,
           "inventory_material_batch_inputs_material_batch_id_fkey"
         )

    drop constraint(
           :inventory_material_batch_inputs,
           "inventory_material_batch_inputs_lot_id_fkey"
         )

    drop_if_exists unique_index(:inventory_material_batch_inputs, [:material_batch_id, :lot_id],
                     name: "inventory_material_batch_inputs_batch_lot_index"
                   )

    drop table(:inventory_material_batch_inputs)

    drop constraint(:inventory_material_batches, "inventory_material_batches_material_id_fkey")

    drop constraint(:inventory_material_batches, "inventory_material_batches_output_lot_id_fkey")

    drop_if_exists unique_index(:inventory_material_batches, [:output_lot_id],
                     name: "inventory_material_batches_output_lot_index"
                   )

    drop_if_exists unique_index(:inventory_material_batches, [:lot_code],
                     name: "inventory_material_batches_lot_code_index"
                   )

    drop table(:inventory_material_batches)

    drop constraint(:inventory_material_recipes, "inventory_material_recipes_material_id_fkey")

    drop_if_exists unique_index(:inventory_material_recipes, [:material_id, :version],
                     name: "inventory_material_recipes_material_version_index"
                   )

    drop table(:inventory_material_recipes)
  end
end
