defmodule Craftplan.Repo.Migrations.AddTraceabilityChain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_production_batches) do
      add :label_snapshot, :map, null: false, default: %{}
    end

    create unique_index(:orders_production_batch_lots, [:production_batch_id, :lot_id],
             name: "orders_production_batch_lots_batch_lot_index"
           )

    alter table(:orders_item_lots) do
      add :order_item_batch_allocation_id,
          references(:orders_item_batch_allocations,
            column: :id,
            name: "orders_item_lots_order_item_batch_allocation_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:orders_item_lots, [:order_item_batch_allocation_id, :lot_id],
             name: "orders_item_lots_allocation_lot_index"
           )

    alter table(:inventory_suppliers) do
      add :address, :map
    end

    alter table(:inventory_lots) do
      add :supplier_lot_code, :text

      add :purchase_order_item_id,
          references(:inventory_purchase_order_items,
            column: :id,
            name: "inventory_lots_purchase_order_item_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:inventory_lots, [:purchase_order_item_id],
             name: "inventory_lots_purchase_order_item_id_index"
           )

    create index(:inventory_lots, [:supplier_lot_code],
             name: "inventory_lots_supplier_lot_code_index"
           )
  end

  def down do
    drop constraint(:inventory_lots, "inventory_lots_purchase_order_item_id_fkey")

    drop_if_exists index(:inventory_lots, [:supplier_lot_code],
                     name: "inventory_lots_supplier_lot_code_index"
                   )

    drop_if_exists index(:inventory_lots, [:purchase_order_item_id],
                     name: "inventory_lots_purchase_order_item_id_index"
                   )

    alter table(:inventory_lots) do
      remove :purchase_order_item_id
      remove :supplier_lot_code
    end

    alter table(:inventory_suppliers) do
      remove :address
    end

    drop constraint(:orders_item_lots, "orders_item_lots_order_item_batch_allocation_id_fkey")

    drop_if_exists unique_index(:orders_item_lots, [:order_item_batch_allocation_id, :lot_id],
                     name: "orders_item_lots_allocation_lot_index"
                   )

    alter table(:orders_item_lots) do
      remove :order_item_batch_allocation_id
    end

    drop_if_exists unique_index(:orders_production_batch_lots, [:production_batch_id, :lot_id],
                     name: "orders_production_batch_lots_batch_lot_index"
                   )

    alter table(:orders_production_batches) do
      remove :label_snapshot
    end
  end
end
