defmodule Craftplan.Repo.Migrations.AddLabelDurabilityType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_products) do
      add :durability_type, :text, null: false, default: "best_before"
    end
  end

  def down do
    alter table(:catalog_products) do
      remove :durability_type
    end
  end
end
