defmodule Craftplan.Repo.Migrations.AddArchivedAtToMaterials do
  @moduledoc """
  Add an optional `archived_at` to `inventory_materials` so operators can
  hide obsolete materials from working views without losing the FK-protected
  history (movements, lots, BOM components).

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_materials) do
      add :archived_at, :utc_datetime
    end

    create index(:inventory_materials, [:archived_at],
             where: "archived_at IS NULL",
             name: "inventory_materials_active_index"
           )
  end

  def down do
    drop_if_exists index(:inventory_materials, [:archived_at],
                     name: "inventory_materials_active_index"
                   )

    alter table(:inventory_materials) do
      remove :archived_at
    end
  end
end
