defmodule Craftplan.Repo.Migrations.AddPriceUpdatedAtToMaterials do
  @moduledoc """
  Add `price_updated_at` to `inventory_materials` so the UI (and audit views)
  can show when each material's price last changed. Auto-stamped by the
  Material `:update` action whenever `price` is in the changeset, including
  the path where `PurchaseOrder.receive` writes the most-recent lot's
  `unit_cost` back to `Material.price`.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_materials) do
      add :price_updated_at, :utc_datetime
    end
  end

  def down do
    alter table(:inventory_materials) do
      remove :price_updated_at
    end
  end
end
