defmodule Craftplan.Repo.Migrations.AddUnitCostToLots do
  @moduledoc """
  Add an optional `unit_cost` to `inventory_lots` so the price paid per unit
  is captured on each receipt and frozen with the lot. Foundation for
  material-cost-over-time reporting.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_lots) do
      add :unit_cost, :decimal
    end
  end

  def down do
    alter table(:inventory_lots) do
      remove :unit_cost
    end
  end
end
