defmodule Craftplan.Repo.Migrations.ReadableBatchSheet do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      add :batch_sheet_scientific_notation, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:settings) do
      remove :batch_sheet_scientific_notation
    end
  end
end
