defmodule Craftplan.Repo.Migrations.AddExternalSkuToMaterials do
  @moduledoc """
  Add an optional `external_sku` to `inventory_materials` so supplier product
  codes (e.g. IGF 34998) can be looked up during invoice import.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_materials) do
      add :external_sku, :text
    end

    create unique_index(:inventory_materials, [:external_sku],
             name: "inventory_materials_external_sku_index"
           )
  end

  def down do
    drop_if_exists unique_index(:inventory_materials, [:external_sku],
                     name: "inventory_materials_external_sku_index"
                   )

    alter table(:inventory_materials) do
      remove :external_sku
    end
  end
end
