defmodule Craftplan.Repo.Migrations.AddApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:accounts_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :prefix, :text, null: false
      add :key_hash, :text, null: false
      add :scopes, :map, null: false, default: %{}
      add :last_used_at, :utc_datetime
      add :revoked_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:accounts_users,
            column: :id,
            name: "accounts_api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:accounts_api_keys, [:key_hash], name: "accounts_api_keys_key_hash_index")
  end

  def down do
    drop_if_exists unique_index(:accounts_api_keys, [:key_hash],
                     name: "accounts_api_keys_key_hash_index"
                   )

    drop constraint(:accounts_api_keys, "accounts_api_keys_user_id_fkey")

    drop table(:accounts_api_keys)
  end
end
