defmodule Craftplan.Repo.Migrations.CascadeProductRecipeDeletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:catalog_labor_steps, "catalog_labor_steps_bom_id_fkey")

    alter table(:catalog_labor_steps) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "catalog_labor_steps_bom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:catalog_boms, "catalog_boms_product_id_fkey")

    alter table(:catalog_boms) do
      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "catalog_boms_product_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:catalog_bom_rollups, "catalog_bom_rollups_product_id_fkey")

    drop constraint(:catalog_bom_rollups, "catalog_bom_rollups_bom_id_fkey")

    alter table(:catalog_bom_rollups) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "catalog_bom_rollups_bom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "catalog_bom_rollups_product_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:catalog_bom_components, "catalog_bom_components_bom_id_fkey")

    alter table(:catalog_bom_components) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "catalog_bom_components_bom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:catalog_bom_components, "catalog_bom_components_bom_id_fkey")

    alter table(:catalog_bom_components) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "catalog_bom_components_bom_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:catalog_bom_rollups, "catalog_bom_rollups_bom_id_fkey")

    drop constraint(:catalog_bom_rollups, "catalog_bom_rollups_product_id_fkey")

    alter table(:catalog_bom_rollups) do
      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "catalog_bom_rollups_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "catalog_bom_rollups_bom_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:catalog_boms, "catalog_boms_product_id_fkey")

    alter table(:catalog_boms) do
      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "catalog_boms_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:catalog_labor_steps, "catalog_labor_steps_bom_id_fkey")

    alter table(:catalog_labor_steps) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "catalog_labor_steps_bom_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
